edition = "2021"
version = "Two"
max_width = 100
unstable_features = true
newline_style = "Unix"
tab_spaces = 2
hard_tabs = false
imports_granularity = "Item"
imports_layout = "HorizontalVertical"
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true
condense_wildcard_suffixes = true
force_multiline_blocks = true
format_macro_matchers = true
format_strings = true
reorder_impl_items = true
use_field_init_shorthand = true
