providers = ["rust"]

[phases.setup]
nixpkgsArchive = '0a4206a51b386e5cda731e8ac78d76ad924c7125'
nixOverlays = ['https://github.com/oxalica/rust-overlay/archive/master.tar.gz']
nixPkgs = ["...", "cargo-make", "deno"]

[phases.build]
cmds = ["cargo make leptos:build"]

[start]
cmd = "./target/server/release/spinnybox_com"
