providers = ["rust"]

[phases.setup]
nixpkgsArchive = '9b8e5abb18324c7fe9f07cb100c3cd4a29cda8b8'
nixOverlays = ['https://github.com/oxalica/rust-overlay/archive/master.tar.gz']
nixPkgs = ["...", "cargo-make", "deno"]

[phases.build]
cmds = ["cargo make leptos:build"]

[start]
cmd = "./target/server/release/spinnybox_com"
