providers = ["rust"]

[phases.setup]
nixpkgsArchive = 'd59c85209d3d43b9867694b5c747db32ce977c7e'
nixOverlays = ['https://github.com/oxalica/rust-overlay/archive/master.tar.gz']
nixPkgs = ["...", "cargo-make", "deno"]

[phases.build]
cmds = ["cargo make leptos:build"]

[start]
cmd = "./target/server/release/spinnybox_com"
