[toolchain]
channel = "nightly-2023-02-06" # https://rust-lang.github.io/rustup-components-history/
profile = "default"
targets = [
  "wasm32-unknown-emscripten",
  "wasm32-unknown-unknown",
  "wasm32-wasi",
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "aarch64-linux-android",
  "aarch64-apple-ios",
  "armv7-linux-androideabi",
  "i686-linux-android",
  "x86_64-linux-android",
  # "i686-unknown-linux-gnu",
  "x86_64-unknown-linux-gnu",
  "i686-pc-windows-gnu",
  "x86_64-pc-windows-gnu",
  "i686-pc-windows-msvc",
  "x86_64-pc-windows-msvc",
]
