[package]
name = "fundraiser_client"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-client = { workspace = true }
anchor-gen = { workspace = true }
