name: devenv
description: Setup development environment with devenv
inputs:
  github-token:
    description: Provide a github token
    required: true
  nix-cache:
    description: The location of the nix cache
    required: true

runs:
  using: composite
  steps:
    - name: install nix
      uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ inputs.github-token }}

    - name: import nix store cache
      if: steps.nix-cache.outputs.cache-hit == 'true'
      run: |
        nix-store --import < ${{ inputs.nix-cache }}
      shell: bash

    - name: enable cachix
      uses: cachix/cachix-action@v12
      with:
        name: devenv

    - name: install devenv.sh
      run: |
        cachix use devenv
        nix profile install --accept-flake-config github:cachix/devenv/v0.6
      shell: bash

    - name: run devenv in ci
      run: devenv ci
      shell: bash

    - name: update paths
      run: devenv shell setup:ci
      shell: bash

    - name: flutter install
      uses: subosito/flutter-action@v2
      with:
        channel: "beta"

    - name: install flutter game dependencies
      run: |
        cd games/2d
        flutter pub get
      shell: bash

    - name: export nix store cache
      if: steps.nix-cache.outputs.cache-hit != 'true'
      run: |
        nix-store --export $(find /nix/store -maxdepth 1 -name '*-*')> ${{ inputs.nix-cache }}
      shell: bash
