name: devenv
description: Setup development environment with devenv
inputs:
  github-token:
    description: Provide a github token
    required: true
  nix-cache:
    description: The location of the nix cache
    required: true

runs:
  using: composite
  steps:
    - name: cache nix store
      uses: actions/cache@v3
      id: nix-cache
      with:
        path: ${{ inputs.nix-cache }}
        key: ${{ runner.os }}-nix-cache-${{ hashFiles('**/devenv.nix', '**/devenv.yaml', '**/devenv.lock') }}
        restore-keys: ${{ runner.os }}-nix-cache-

    - name: install nix
      uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ inputs.github-token }}

    - name: import nix store cache
      if: steps.nix-cache.outputs.cache-hit == 'true'
      run: |
        nix-store --import < ${{ inputs.nix-cache }}
      shell: bash

    - name: enable cachix
      uses: cachix/cachix-action@v12
      with:
        name: devenv

    - name: install devenv.sh
      run: |
        cachix use devenv
        nix profile install --accept-flake-config github:cachix/devenv/v0.6.2
      shell: bash

    - name: run devenv in ci
      run: devenv ci
      shell: bash

    - name: update paths
      run: devenv shell setup:ci
      shell: bash

    - name: flutter install
      uses: subosito/flutter-action@v2
      with:
        channel: beta

    - name: install flutter dependencies
      run: |
        flutter pub global activate melos 3.0.0
        melos bootstrap
      shell: bash

    - name: export nix store cache
      if: steps.nix-cache.outputs.cache-hit != 'true'
      run: |
        nix-store --export $(find /nix/store -maxdepth 1 -name '*-*')> ${{ inputs.nix-cache }}
      shell: bash
