name: devenv
description: Setup development environment with devenv
inputs:
  github-token:
    description: Provide a github token
    required: true

runs:
  using: composite
  steps:
    - name: cache nix store
      uses: actions/cache@v3
      id: nix-cache
      with:
        path: /tmp/nixcache
        key: ${{ runner.os }}-nix-cache

    - name: cache flutter dependencies
      uses: actions/cache@v2
      with:
        path: ${{ runner.tool_cache }}/flutter
        key: ${{ runner.os }}-flutter-beta-stable

    - name: install nix
      uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ inputs.github-token }}

    - name: import nix store cache
      if: steps.nix-cache.outputs.cache-hit == 'true'
      run: |
        nix-store --import < /tmp/nixcache
      shell: bash

    - name: enable cachix
      uses: cachix/cachix-action@v12
      with:
        name: devenv

    - name: install devenv.sh
      run: nix profile install github:cachix/devenv/v0.5.1
      shell: bash

    - name: run devenv in ci
      run: devenv ci
      shell: bash

    - name: update paths
      run: devenv shell setup:ci
      shell: bash

    - name: flutter install
      uses: subosito/flutter-action@v2
      with:
        channel: "beta"

    # currently melos doesn't work with dart 3 which is used in flutter beta
    - name: setup melos
      uses: bluefireteam/melos-action@v1

    - name: install flutter game dependencies
      run: |
        cd games/2d
        flutter pub get
      shell: bash

    - name: export nix store cache
      if: steps.nix-cache.outputs.cache-hit != 'true'
      run: |
        nix-store --export $(find /nix/store -maxdepth 1 -name '*-*')> /tmp/nixcache
      shell: bash
