[package]
name = "dodge"
version = "0.0.0"
authors = ["Ifiok Jr. <ifiokotung@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
gdnative = { workspace = true }
rand = { workspace = true }
