name: spinnybox_2d
description: Think different. Play different.
publish_to: "none"

version: 0.0.0+1

environment:
  sdk: ">=3.0.0-218.1.beta <4.0.0"

dependencies:
  audioplayers: ^4.0.1
  badges: ^3.1.1
  cupertino_icons: ^1.0.5
  flame_audio: ^2.0.2
  flame_rive: ^1.7.1
  flame_svg: ^1.7.3
  flame: ^1.7.3
  flutter_hooks: ^0.18.6
  flutter_markdown: ^0.6.14
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  functional_widget_annotation: ^0.10.0
  go_router: ^6.5.8
  hooks_riverpod: ^2.3.6
  logging: ^1.1.1
  nanoid: ^1.0.0
  rive: ^0.10.4
  riverpod_annotation: ^2.1.1
  rxdart: ^0.27.7
  sensors_plus: ^2.0.5
  share_plus: ^6.3.4
  shared_preferences: ^2.1.0
  wakelock: ^0.6.2

  firebase_core: ^2.10.0 # Needed for Crashlytics below
  firebase_crashlytics: ^3.1.2 # Error reporting
  games_services: ^3.0.1 # Achievements and leaderboards
  in_app_purchase: ^3.1.5 # In-app purchases

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.1
  build_verify: ^3.1.0
  custom_lint: ^0.3.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.19
  functional_widget: ^0.10.1
  go_router_builder: ^1.2.2
  json_serializable: ^6.6.1
  lint: ^2.1.1
  riverpod_generator: ^2.2.1
  riverpod_lint: ^1.3.1
  freezed: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/svg/
    - assets/svg/game/
    - assets/svg/game/background/
    - assets/svg/game/player/
    - assets/svg/game/obstacles/
    - assets/svg/game/character/
    - assets/svg/icons/
    - assets/svg/ui/
    - assets/images/

  fonts:
    - family: GloriaHallelujah
      fonts:
        - asset: assets/fonts/GloriaHallelujah-Regular.ttf

flutter_native_splash:
  image: assets/images/splash_screen_image_light.png
  color: "#ffffff"
  image_dark: assets/images/splash_screen_image_dark.png
  color_dark: "#313131"
  android_gravity: center
  ios_content_mode: center

flutter_icons:
  image_path: assets/images/logo.png
  android: true
  ios: true
  remove_alpha_ios: true
